### PR TITLE
Enable access to Test Run ID

### PR DESCRIPTION
**Pull request by timotei**
In order to do advanced work with the XTC Run ID, we need to get it first, so this PR helps in that direction.

### CODE REVIEW

**Comment by godrei** [comment]
Hi @timotei ,

We’ve checked and it seems your changes are only working if you set the —async-json flag, otherwise it will fail. Because the flag is an optional parameter we can’t merge in your step currently.

You can still use your own version in a forked repository in the following way:
- fork this repo
- push your changes in your fork
- you can use your forked step as:

If your original step in your bitrise.yml looks something like that:

```
- xamarin-test-cloud-for-ios:
   title: Original xamarin-test-cloud-for-ios
   inputs:
   - xamarin_user: $USER
   - test_cloud_api_key: $API_KEY
   - test_cloud_devices: $DEVICES
   - test_cloud_is_async: $ASYNC
   - test_cloud_series: $SERIES
   - test_cloud_parallelization: $PARALLELIZATION
   - other_parameters: $OTHER_PARAMETERS
```

then with your forked version of step:

```
- git::https://github.com/YOUR_USER/YOUR_steps-xamarin-test-cloud-for-ios_FORK.git@YOUR_BRANCH:
   title: Forked xamarin-test-cloud-for-ios
   inputs:
   - xamarin_user: $USER
   - test_cloud_api_key: $API_KEY
   - test_cloud_devices: $DEVICES
   - test_cloud_is_async: $ASYNC
   - test_cloud_series: $SERIES
   - test_cloud_parallelization: $PARALLELIZATION
   - other_parameters: $OTHER_PARAMETERS
```

You can see more examples with direct-url steps at: https://github.com/bitrise-io/bitrise/blob/master/_examples/tutorials/steps-and-workflows/bitrise.yml#L65

Also can you please give us a couple of use cases about the Test Run ID. How it can be used for further steps.

Thanks!

**Comment by timotei** [comment]
Yeah, the flag is needed. Should we try and solve this somehow (by informing the user about it and then hardcode it it the testcloud id is needed) or it's a no-no? I already use my own fork but I thought it might be useful for everyone to have this functionality :)

**Comment by godrei** [comment]
Hi @timotei ,
sorry for my late response.
I managed to wire in the `test run id` export.

Some details:
- `test_cloud_is_async` is by default `yes`, now this add `--async-json` flag to `test-cloud` command, so output contains the json result with `TestRunId` and also the default is still async upload.
- async json output contains `ErrorMessages` key, if it has value step fails with that errors.
- somehow json output is not a pure json output, so instead of json parsing i use regex, for output filtering.

```
...
Uploading Simple Credit Card Validator.ipa... 100%
Uploading Simple Credit Card Validator.ipa... 100%
{"Log":["Negotiating file upload to Xamarin Test Cloud.","Posting to https://testcloud.xamarin.com/ci/upload2\n","Uploading CreditCardValidator.iOS.UITests.dll ... Already uploaded.","Uploading Xamarin.UITest.dll ... Already uploaded.","Uploading nunit.framework.dll ... Already uploaded.","Uploading CreditCardValidator.iOS ... Already uploaded.","\nUpload complete.\n","Skipping wait for cloud execution. Upload Id: ***"],"ErrorMessages":[],"TestRunId":"***","LaunchUrl":null}
```

However if you want to be a bitrise contributor, feel free to copy my [changes](https://github.com/bitrise-steplib/steps-xamarin-test-cloud-for-ios/pull/22) and create a new PR.

Thanks for the contribution!

**Comment by timotei** [comment]
Well, I _wanted_ to be a contributor, hence the PR and waited for feedback on how we'd like to do (polish) the impl.

But it seems you already merged the functionality by doing another PR. Pretty opposite behavior (unprofessional) to what open-source means, if you ask me. It's pretty sad; so I will probably not contribute anymore to bitrise's open source components if this is a standard behavior.

**Comment by viktorbenei** [comment]
First of all we're terribly sorry @timotei . We didn't want you to feel left out, and we certainly don't want to discourage you in your future contributions.

What happened: as you can see in the PR @godrei referenced - https://github.com/bitrise-steplib/steps-xamarin-test-cloud-for-ios/pull/22 - we were working on significant changes in the step. This required changes which would require your PR to be rewritten to fit into the new code.

While @godrei was working on the changes he tested your solution and reported his concerns (https://github.com/bitrise-steplib/steps-xamarin-test-cloud-for-ios/pull/15#issuecomment-193215665). He tested your code while he was working on the other changes and decided to adapt it to fit into the new code structure, so that the new version of the step can be released.

He reported this about 9 days ago (https://github.com/bitrise-steplib/steps-xamarin-test-cloud-for-ios/pull/15#issuecomment-222734626) and waited for a reply, but as the change was part of an important new release of the Step we decided to ship the changes as you did not raise any concerns.

We of course recognise your contribution and we're really thankful for it! Please keep up the great work you do! We also recognise that the wording of https://github.com/bitrise-steplib/steps-xamarin-test-cloud-for-ios/pull/15#issuecomment-222734626 was not perfect, we'll make sure that our communication is better in the future.

Please let us know if you have any suggestion regarding this matter, or if we can do anything for you, and please keep up the awesome work you do in the FOSS space!

**Pull request closed without merging**
